database:
  type: "sqlite"  # other options: "postgresql", "mysql"
  sqlite:
    db_file: "resources/MFA_analysis.db"
  postgresql:
    host: "dpg-csheilaj1k6c7396lgq0-a.ohio-postgres.render.com"
    port: 5432
    user: "mf_analysis_user"
    password: "Ie3DuiGoogJwndjXLQYX9irXcUJnVtUk"
    database: "mf_analysis"
  mysql:
    host: "localhost"
    port: 3306
    user: "your_user"
    password: "your_password"
    database: "your_db"
