KEGG_PATHWAY_DICT = {"Metabolism": {
        "Global and overview maps": [
            "Metabolic pathways",
            "Biosynthesis of secondary metabolites",
            "Microbial metabolism in diverse environments",
            "Carbon metabolism",
            "2-Oxocarboxylic acid metabolism",
            "Fatty acid metabolism",
            "Biosynthesis of amino acids",
            "Nucleotide metabolism",
            "Biosynthesis of nucleotide sugars",
            "Biosynthesis of cofactors",
            "Degradation of aromatic compounds",
            "Nitrogen cycle"
        ],
        "Carbohydrate metabolism": [
            "Glycolysis / Gluconeogenesis",
            "Citrate cycle (TCA cycle)",
            "Pentose phosphate pathway",
            "Pentose and glucuronate interconversions",
            "Fructose and mannose metabolism",
            "Galactose metabolism",
            "Ascorbate and aldarate metabolism",
            "Starch and sucrose metabolism",
            "Amino sugar and nucleotide sugar metabolism",
            "Pyruvate metabolism",
            "Glyoxylate and dicarboxylate metabolism",
            "Propanoate metabolism",
            "Butanoate metabolism",
            "C5-Branched dibasic acid metabolism",
            "Inositol phosphate metabolism"
        ],
        "Energy metabolism": [
            "Oxidative phosphorylation",
            "Photosynthesis",
            "Photosynthesis - antenna proteins",
            "Carbon fixation by Calvin cycle",
            "Other carbon fixation pathways",
            "Methane metabolism",
            "Nitrogen metabolism",
            "Sulfur metabolism"
        ],
        "Lipid metabolism": [
            "Fatty acid biosynthesis",
            "Fatty acid elongation",
            "Fatty acid degradation",
            "Cutin, suberine and wax biosynthesis",
            "Mycolic acid biosynthesis",
            "Steroid biosynthesis",
            "Primary bile acid biosynthesis",
            "Secondary bile acid biosynthesis",
            "Steroid hormone biosynthesis",
            "Glycerolipid metabolism",
            "Glycerophospholipid metabolism",
            "Ether lipid metabolism",
            "Sphingolipid metabolism",
            "Arachidonic acid metabolism",
            "Linoleic acid metabolism",
            "Alpha-Linolenic acid metabolism",
            "Biosynthesis of unsaturated fatty acids"
        ],
        "Nucleotide metabolism": [
            "Purine metabolism",
            "Pyrimidine metabolism"
        ],
        "Amino acid metabolism": [
            "Alanine, aspartate and glutamate metabolism",
            "Glycine, serine and threonine metabolism",
            "Cysteine and methionine metabolism",
            "Valine, leucine and isoleucine degradation",
            "Valine, leucine and isoleucine biosynthesis",
            "Lysine biosynthesis",
            "Lysine degradation",
            "Arginine biosynthesis",
            "Arginine and proline metabolism",
            "Histidine metabolism",
            "Tyrosine metabolism",
            "Phenylalanine metabolism",
            "Tryptophan metabolism",
            "Phenylalanine, tyrosine and tryptophan biosynthesis"
        ],
        "Metabolism of other amino acids": [
            "Beta-Alanine metabolism",
            "Taurine and hypotaurine metabolism",
            "Phosphonate and phosphinate metabolism",
            "Selenocompound metabolism",
            "Cyanoamino acid metabolism",
            "D-Amino acid metabolism",
            "Glutathione metabolism"
        ],
        "Glycan biosynthesis and metabolism": [
            "N-Glycan biosynthesis",
            "Various types of N-glycan biosynthesis",
            "Mucin type O-glycan biosynthesis",
            "Mannose type O-glycan biosynthesis",
            "Other types of O-glycan biosynthesis",
            "Glycosaminoglycan biosynthesis - chondroitin sulfate / dermatan sulfate",
            "Glycosaminoglycan biosynthesis - heparan sulfate / heparin",
            "Glycosaminoglycan biosynthesis - keratan sulfate",
            "Glycosaminoglycan degradation",
            "Glycosylphosphatidylinositol (GPI)-anchor biosynthesis",
            "Glycosphingolipid biosynthesis - lacto and neolacto series",
            "Glycosphingolipid biosynthesis - globo and isoglobo series",
            "Glycosphingolipid biosynthesis - ganglio series",
            "Other glycan degradation",
            "Lipopolysaccharide biosynthesis",
            "O-Antigen repeat unit biosynthesis",
            "O-Antigen nucleotide sugar biosynthesis",
            "Peptidoglycan biosynthesis",
            "Teichoic acid biosynthesis",
            "Lipoarabinomannan (LAM) biosynthesis",
            "Arabinogalactan biosynthesis - Mycobacterium",
            "Exopolysaccharide biosynthesis"
        ],
        "Metabolism of cofactors and vitamins": [
            "Thiamine metabolism",
            "Riboflavin metabolism",
            "Vitamin B6 metabolism",
            "Nicotinate and nicotinamide metabolism",
            "Pantothenate and CoA biosynthesis",
            "Biotin metabolism",
            "Lipoic acid metabolism",
            "Folate biosynthesis",
            "One carbon pool by folate",
            "Retinol metabolism",
            "Porphyrin metabolism",
            "Ubiquinone and other terpenoid-quinone biosynthesis"
        ],
        "Metabolism of terpenoids and polyketides": [
            "Terpenoid backbone biosynthesis",
            "Monoterpenoid biosynthesis",
            "Sesquiterpenoid and triterpenoid biosynthesis",
            "Diterpenoid biosynthesis",
            "Gibberellin biosynthesis",
            "Carotenoid biosynthesis",
            "Brassinosteroid biosynthesis",
            "Insect hormone biosynthesis",
            "Zeatin biosynthesis",
            "Limonene degradation",
            "Pinene, camphor and geraniol degradation",
            "Type I polyketide structures",
            "Biosynthesis of 12-, 14- and 16-membered macrolides",
            "Biosynthesis of ansamycins",
            "Biosynthesis of type II polyketide backbone",
            "Biosynthesis of type II polyketide products",
            "Biosynthesis of siderophore group nonribosomal peptides"
        ],
        "Biosynthesis of other secondary metabolites": [
            "Phenylpropanoid biosynthesis",
            "Stilbenoid, diarylheptanoid and gingerol biosynthesis",
            "Flavonoid biosynthesis",
            "Flavone and flavonol biosynthesis",
            "Anthocyanin biosynthesis",
            "Isoflavonoid biosynthesis",
            "Degradation of flavonoids",
            "Indole alkaloid biosynthesis",
            "Indole diterpene alkaloid biosynthesis",
            "Isoquinoline alkaloid biosynthesis",
            "Tropane, piperidine and pyridine alkaloid biosynthesis",
            "Biosynthesis of various alkaloids",
            "Caffeine metabolism",
            "Betalain biosynthesis",
            "Glucosinolate biosynthesis",
            "Benzoxazinoid biosynthesis",
            "Penicillin and cephalosporin biosynthesis",
            "Carbapenem biosynthesis",
            "Monobactam biosynthesis",
            "Clavulanic acid biosynthesis",
            "Streptomycin biosynthesis",
            "Neomycin, kanamycin and gentamicin biosynthesis",
            "Acarbose and validamycin biosynthesis",
            "Novobiocin biosynthesis",
            "Staurosporine biosynthesis",
            "Phenazine biosynthesis",
            "Prodigiosin biosynthesis",
            "Aflatoxin biosynthesis",
            "Biosynthesis of various antibiotics",
            "Biosynthesis of various plant secondary metabolites",
            "Biosynthesis of various other secondary metabolites"
        ],
        "Xenobiotics biodegradation and metabolism": [
            "Benzoate degradation",
            "Aminobenzoate degradation",
            "Fluorobenzoate degradation",
            "Chloroalkane and chloroalkene degradation",
            "Chlorocyclohexane and chlorobenzene degradation",
            "Toluene degradation",
            "Xylene degradation",
            "Nitrotoluene degradation",
            "Ethylbenzene degradation",
            "Styrene degradation",
            "Atrazine degradation",
            "Caprolactam degradation",
            "Bisphenol degradation",
            "Dioxin degradation",
            "Naphthalene degradation",
            "Polycyclic aromatic hydrocarbon degradation",
            "Furfural degradation",
            "Steroid degradation",
            "Metabolism of xenobiotics by cytochrome P450",
            "Drug metabolism - cytochrome P450",
            "Drug metabolism - other enzymes"
        ],
        "Chemical structure transformation maps": [
            "Overview of biosynthetic pathways",
            "Biosynthesis of plant secondary metabolites",
            "Biosynthesis of phenylpropanoids",
            "Biosynthesis of terpenoids and steroids",
            "Biosynthesis of alkaloids derived from shikimate pathway",
            "Biosynthesis of alkaloids derived from ornithine, lysine and nicotinic acid",
            "Biosynthesis of alkaloids derived from histidine and purine",
            "Biosynthesis of alkaloids derived from terpenoid and polyketide",
            "Biosynthesis of plant hormones"
        ]
    },
    "Genetic Information Processing": {
        "Transcription": [
            "RNA polymerase",
            "Basal transcription factors",
            "Spliceosome"
        ],
        "Translation": [
            "Ribosome",
            "Aminoacyl-tRNA biosynthesis",
            "Nucleocytoplasmic transport",
            "mRNA surveillance pathway",
            "Ribosome biogenesis in eukaryotes"
        ],
        "Folding, sorting and degradation": [
            "Protein export",
            "Protein processing in endoplasmic reticulum",
            "SNARE interactions in vesicular transport",
            "Ubiquitin mediated proteolysis",
            "Sulfur relay system",
            "Proteasome",
            "RNA degradation"
        ],
        "Replication and repair": [
            "DNA replication",
            "Base excision repair",
            "Nucleotide excision repair",
            "Mismatch repair",
            "Homologous recombination",
            "Non-homologous end-joining",
            "Fanconi anemia pathway"
        ],
        "Chromosome": [
            "ATP-dependent chromatin remodeling",
            "Polycomb repressive complex"
        ],
        "Information processing in viruses": [
            "Viral genome structure",
            "Viral replication",
            "Viral life cycle - HIV-1",
            "Virion - Human immunodeficiency virus",
            "Virion - Rotavirus",
            "Virion - Coronavirus",
            "Virion - Influenza virus",
            "Virion - Enterovirus",
            "Virion - Flavivirus",
            "Virion - Ebolavirus, Lyssavirus and Morbillivirus",
            "Virion - Hepatitis viruses",
            "Virion - Herpesvirus",
            "Virion - Orthopoxvirus",
            "Virion - Adenovirus",
            "Virion - Bacteriophages T4 and T7",
            "Virion - Bacteriophage lambda"
        ]
    },
    "Environmental Information Processing": {
        "Membrane transport": [
            "ABC transporters",
            "Phosphotransferase system (PTS)",
            "Bacterial secretion system"
        ],
        "Signal transduction": [
            "Two-component system",
            "MAPK signaling pathway",
            "MAPK signaling pathway - fly",
            "MAPK signaling pathway - plant",
            "MAPK signaling pathway - yeast",
            "ErbB signaling pathway",
            "Ras signaling pathway",
            "Rap1 signaling pathway",
            "Wnt signaling pathway",
            "Notch signaling pathway",
            "Hedgehog signaling pathway",
            "Hedgehog signaling pathway - fly",
            "TGF-beta signaling pathway",
            "Hippo signaling pathway",
            "Hippo signaling pathway - fly",
            "Hippo signaling pathway - multiple species",
            "VEGF signaling pathway",
            "Apelin signaling pathway",
            "JAK-STAT signaling pathway",
            "NF-kappa B signaling pathway",
            "TNF signaling pathway",
            "HIF-1 signaling pathway",
            "FoxO signaling pathway",
            "Calcium signaling pathway",
            "Phosphatidylinositol signaling system",
            "Phospholipase D signaling pathway",
            "Sphingolipid signaling pathway",
            "cAMP signaling pathway",
            "cGMP-PKG signaling pathway",
            "PI3K-Akt signaling pathway",
            "AMPK signaling pathway",
            "mTOR signaling pathway",
            "Plant hormone signal transduction"
        ],
        "Signaling molecules and interaction": [
            "Neuroactive ligand-receptor interaction",
            "Cytokine-cytokine receptor interaction",
            "Viral protein interaction with cytokine and cytokine receptor",
            "ECM-receptor interaction",
            "Cell adhesion molecules"
        ]
    },
    "Cellular Processes": {
        "Transport and catabolism": [
            "Endocytosis",
            "Phagosome",
            "Lysosome",
            "Peroxisome",
            "Autophagy - animal",
            "Autophagy - yeast",
            "Autophagy - other",
            "Mitophagy - animal",
            "Mitophagy - yeast",
            "Efferocytosis"
        ],
        "Cell growth and death": [
            "Cell cycle",
            "Cell cycle - yeast",
            "Cell cycle - Caulobacter",
            "Meiosis - yeast",
            "Oocyte meiosis",
            "Apoptosis",
            "Apoptosis - fly",
            "Apoptosis - multiple species",
            "Ferroptosis",
            "Necroptosis",
            "p53 signaling pathway",
            "Cellular senescence"
        ],
        "Cellular community - eukaryotes": [
            "Focal adhesion",
            "Adherens junction",
            "Tight junction",
            "Gap junction",
            "Signaling pathways regulating pluripotency of stem cells"
        ],
        "Cellular community - prokaryotes": [
            "Quorum sensing",
            "Biofilm formation - Vibrio cholerae",
            "Biofilm formation - Pseudomonas aeruginosa",
            "Biofilm formation - Escherichia coli"
        ],
        "Cell motility": [
            "Bacterial chemotaxis",
            "Flagellar assembly",
            "Motor proteins",
            "Cytoskeleton in muscle cells",
            "Regulation of actin cytoskeleton"
        ]
    },
    "Organismal Systems": {
        "Immune system": [
            "Hematopoietic cell lineage",
            "Complement and coagulation cascades",
            "Platelet activation",
            "Neutrophil extracellular trap formation",
            "Toll-like receptor signaling pathway",
            "Toll and Imd signaling pathway",
            "NOD-like receptor signaling pathway",
            "RIG-I-like receptor signaling pathway",
            "Cytosolic DNA-sensing pathway",
            "C-type lectin receptor signaling pathway",
            "Natural killer cell mediated cytotoxicity",
            "Antigen processing and presentation",
            "T cell receptor signaling pathway",
            "Th1 and Th2 cell differentiation",
            "Th17 cell differentiation",
            "IL-17 signaling pathway",
            "B cell receptor signaling pathway",
            "Fc epsilon RI signaling pathway",
            "Fc gamma R-mediated phagocytosis",
            "Leukocyte transendothelial migration",
            "Intestinal immune network for IgA production",
            "Chemokine signaling pathway"
        ],
        "Endocrine system": [
            "Insulin secretion",
            "Insulin signaling pathway",
            "Glucagon signaling pathway",
            "Regulation of lipolysis in adipocytes",
            "Adipocytokine signaling pathway",
            "PPAR signaling pathway",
            "GnRH secretion",
            "GnRH signaling pathway",
            "Ovarian steroidogenesis",
            "Estrogen signaling pathway",
            "Progesterone-mediated oocyte maturation",
            "Prolactin signaling pathway",
            "Oxytocin signaling pathway",
            "Relaxin signaling pathway",
            "Growth hormone synthesis, secretion and action",
            "Thyroid hormone synthesis",
            "Thyroid hormone signaling pathway",
            "Parathyroid hormone synthesis, secretion and action",
            "Melanogenesis",
            "Renin secretion",
            "Renin-angiotensin system",
            "Aldosterone synthesis and secretion",
            "Cortisol synthesis and secretion"
        ],
        "Circulatory system": [
            "Cardiac muscle contraction",
            "Adrenergic signaling in cardiomyocytes",
            "Vascular smooth muscle contraction"
        ],
        "Digestive system": [
            "Salivary secretion",
            "Gastric acid secretion",
            "Pancreatic secretion",
            "Bile secretion",
            "Carbohydrate digestion and absorption",
            "Protein digestion and absorption",
            "Fat digestion and absorption",
            "Cholesterol metabolism",
            "Vitamin digestion and absorption",
            "Cobalamin transport and metabolism",
            "Mineral absorption"
        ],
        "Excretory system": [
            "Vasopressin-regulated water reabsorption",
            "Aldosterone-regulated sodium reabsorption",
            "Endocrine and other factor-regulated calcium reabsorption",
            "Proximal tubule bicarbonate reclamation",
            "Collecting duct acid secretion"
        ],
        "Nervous system": [
            "Glutamatergic synapse",
            "GABAergic synapse",
            "Cholinergic synapse",
            "Dopaminergic synapse",
            "Serotonergic synapse",
            "Long-term potentiation",
            "Long-term depression",
            "Retrograde endocannabinoid signaling",
            "Synaptic vesicle cycle",
            "Neurotrophin signaling pathway"
        ],
        "Sensory system": [
            "Phototransduction",
            "Phototransduction - fly",
            "Olfactory transduction",
            "Taste transduction",
            "Inflammatory mediator regulation of TRP channels"
        ],
        "Development and regeneration": [
            "Dorso-ventral axis formation",
            "Axon guidance",
            "Axon regeneration",
            "Osteoclast differentiation"
        ],
        "Aging": [
            "Longevity regulating pathway",
            "Longevity regulating pathway - worm",
            "Longevity regulating pathway - multiple species"
        ],
        "Environmental adaptation": [
            "Circadian rhythm",
            "Circadian entrainment",
            "Circadian rhythm - fly",
            "Circadian rhythm - plant",
            "Thermogenesis",
            "Plant-pathogen interaction"
        ]
    }
}